{% set name = "nr.fs" %}
{% set version = "1.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nr.fs-{{ version }}.tar.gz
  sha256: 788aa0a04c4143f95c5245bc8ccc0c0872e932be533bd37780fbb55afcdf124a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - six >=1.11.0,<2.0.0

test:
  imports:
    - nr
    - nr.fs
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.niklasrosenstein.com/NiklasRosenstein/nr
  summary: Filesystem and path manipulation tools.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - NiklasRosenstein
